directories:
  "app/controllers":
    IrresponsibleModule:
      enabled: false
    NestedIterators:
      max_allowed_nesting: 2
    UnusedPrivateMethod:
      enabled: false
    UncommunicativeModuleName:
      enabled: false
    TooManyStatements:
      max_statements: 10
    InstanceVariableAssumption:
      enabled: false
  "app/mailers":
    IrresponsibleModule:
      enabled: false
    NestedIterators:
      max_allowed_nesting: 2
    UnusedPrivateMethod:
      enabled: false
    UncommunicativeModuleName:
      enabled: false
    TooManyStatements:
      max_statements: 10
    InstanceVariableAssumption:
      enabled: false
  "app/serializers":
    IrresponsibleModule:
      enabled: false
    NestedIterators:
      max_allowed_nesting: 2
    UnusedPrivateMethod:
      enabled: false
    UncommunicativeModuleName:
      enabled: false
    TooManyStatements:
      max_statements: 10
    UtilityFunction:
      enabled: false
  "app/policies":
    IrresponsibleModule:
      enabled: false
    NestedIterators:
      max_allowed_nesting: 2
    UnusedPrivateMethod:
      enabled: false
  "app/models":
    IrresponsibleModule:
      enabled: false
    RepeatedConditional:
      enabled: false
    Attribute:
      enabled: false
  "app/helpers":
    IrresponsibleModule:
      enabled: false
    UtilityFunction:
      enabled: false
    ControlParameter:
      enabled: false
    DuplicateMethodCall:
      enabled: false
    FeatureEnvy:
      enabled: false
    TooManyStatements:
      max_statements: 10
  "app/channels":
    IrresponsibleModule:
      enabled: false
    NestedIterators:
      max_allowed_nesting: 2
    UnusedPrivateMethod:
      enabled: false
  "app/jobs":
    IrresponsibleModule:
      enabled: false
    NestedIterators:
      max_allowed_nesting: 2
    UnusedPrivateMethod:
      enabled: false
  "spec/features":
    DuplicateMethodCall:
      enabled: false
    TooManyStatements:
      max_statements: 8
  "spec":
    UtilityFunction:
      enabled: false

detectors:
  NilCheck:
    enabled: false

  DuplicateMethodCall:
    max_calls: 3

  UtilityFunction:
    public_methods_only: true

exclude_paths:
  - db/migrate
  - node_modules
  - test
  - app/controllers/wrap